# NUMPY

In [1]:
# Numpy is the most important library in the Python.
# NumPy is a powerful Python library for numerical computing.
# It provides support for large, multi-dimensional arrays and matrices, 
# along with mathematical functions to operate on these arrays efficiently. 

In [2]:
a = [1,2,3]
b = [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [3]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [8]:
import numpy as np
a = np.array([1,2,3], ndmin=5)
a.ndim

5

In [20]:
import numpy as np

a = np.array(([1,2],[3,4],[5,6]),ndmin=4)
print(a)
print(a.ndim)
print(a.shape)

[[[[1 2]
   [3 4]
   [5 6]]]]
4
(1, 1, 3, 2)


In [6]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [7]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [13]:
import numpy as np
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
import numpy as np
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
import numpy as np
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [23]:
import numpy as np
a = np.arange(0,30,3)
print(a)

[ 0  3  6  9 12 15 18 21 24 27]


In [28]:
import numpy as np
a = np.eye(5,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [34]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[2,1]])
print(np.dot(A,B))


[[ 9  8]
 [23 22]]


In [36]:
import numpy as np
a = np.full([3,3],10)
print(a)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [11]:
import numpy as np
print(np.zeros((3,3)))
#--------------------
print(np.ones((5,6)))
#--------------------
print(np.eye(3,5))
#--------------------
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))
#--------------------
print(np.full((3,3),9))
#---------------------
print(np.linspace(0,10,6))
#---------------------
print(np.arange(0,10,1))
#---------------------
print(np.random.rand(3,3))
#----------------------
print(np.random.randn(4,4))
#------------------
print(np.random.randint(1,10,(3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[19 22]
 [43 50]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[ 0.  2.  4.  6.  8. 10.]
[0 1 2 3 4 5 6 7 8 9]
[[0.16154823 0.70236598 0.65285906]
 [0.36427343 0.51112346 0.1114912 ]
 [0.07421102 0.98750495 0.49578006]]
[[-0.2797874   0.38622166  0.16212237 -0.21720402]
 [-0.69752043  0.24376217 -1.55022373 -0.51413771]
 [ 0.06493252  0.44119862 -0.34121971  0.51070938]
 [-0.10869449  0.09591712 -0.10589503  0.27762649]]
[[9 2 3]
 [6 2 4]
 [5 3 9]]


# Important Array Methods

In [12]:
# numpy provide several useful functions to analyze arrays:

In [13]:
a = " Hello i am good"
a.split()

['Hello', 'i', 'am', 'good']

In [16]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
a = np.split(arr,[0,2,3])
print(a)

[array([], dtype=int64), array([1, 2]), array([3]), array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]


In [28]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.argmax())
print(arr.argmin())
print(np.var(arr))
print(np.std(arr))
print(np.median(arr))
print(arr.mean())

120
15
1
14
0
18.666666666666668
4.320493798938574
8.0
8.0


In [40]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
arr.ndim
print(arr.reshape(3,2))
print(arr.ravel())
arr.flatten()
print(arr.T)
arr
print(np.expand_dims(arr,axis=0))
a =np.array([[1,2,3,4]])
print(np.squeeze(a))

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[[1 2 3]
  [4 5 6]]]
[1 2 3 4]


# Broadcasting in numpy

In [42]:
# Broadcasting allows Numpy to perform operations on arrays of different shapes.


In [44]:
# Broadcasting example
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([1,2,3])
C = A + B
print(C)

[[2 4 6]
 [5 7 9]]


# Row-Major and Column-Major Storage

In [46]:
#Numpy Stores arrays in row-major order by default, but you can change it to column -major using='f'.

In [56]:
# Row-major vs Column-major

arr = np.array([[1,2],[3,4],[5,6]],order='C')
print(arr.shape)
arr
arr1 =np.array([[1,2,3],[3,4,5],[5,6,7]],order='F')
print(arr1.shape)
arr1
print('Row-major:',arr.flatten(order='C'))
print('Column-major:',arr1.flatten(order='F'))

(3, 2)
(3, 3)
Row-major: [1 2 3 4 5 6]
Column-major: [1 3 5 2 4 6 3 5 7]


# Array Attributes

In [57]:
# Some important attributes of Numpy arrays include:

In [59]:
# Array attributes
arr =np.array([[1,2,3],[4,5,6]])
print('Shape:', arr.shape)
print('Number of dimensions:',arr.ndim)

Shape: (2, 3)
Number of dimensions: 2


# Concept of Axis in Numpy

In [61]:
# Axis 0 refers to rows (vertical operations), while Axis 1 refers to columns (horizontal operations).

In [62]:
arr = np.array([[1,2],[3,4]])
print('Sum along axis 0:', arr.sum(axis=0))
print('Sum along axis 1:',arr.sum(axis=1))

Sum along axis 0: [4 6]
Sum along axis 1: [3 7]


# Reshaping Arrays

In [65]:
# We can reshape arrays into different dimensions. 

In [70]:
# Reshaping example
arr = np.arange(6).reshape(2,3)
print(arr)

[[0 1 2]
 [3 4 5]]


# Splitting Arrays

In [71]:
# Numpy provides functions to split arrays into multiple parts.

In [75]:
# Splitting an array
arr = np.array([1,2,3,4,5,6,7,8,9])
split_arr = np.split(arr,3)
print(split_arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


# hsplit vs vsplit

In [77]:
# hsplit() splits along columns (horizontally), vsplit() splits along rows(vertically)

In [78]:
# hsplit vs vsplit
arr = np.arange(16).reshape(4,4)
print(arr)
print('Horizontal Split:', np.hsplit(arr,2))
print('Vertical Split:',np.vsplit(arr,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizontal Split: [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
Vertical Split: [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# Stacking Arrays

In [79]:
# Numpy allows stacking vertically and horizontally.

In [81]:
# Stacking arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
print('Horizontal Stack:',np.hstack((a,b)))
print('Vertical Stack:',np.vstack((a,b)))

Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack: [[1 2 3]
 [4 5 6]]


In [82]:
import numpy as np
a = np.array([5],ndmin=10)
print(a)

[[[[[[[[[[5]]]]]]]]]]


In [85]:
#1 how do you create a numpy array from a python list and specify the data types?
import numpy as np
list1 = [1,2,3,4,5]
arr = np.array(list1,dtype = float)
print(arr)

[1. 2. 3. 4. 5.]


In [88]:
#2 how do you generate an array of evenly spaced numbers?
import numpy as np
print(np.linspace(0,10,6))
print(np.arange(0,10,1))

[ 0.  2.  4.  6.  8. 10.]
[0 1 2 3 4 5 6 7 8 9]


In [89]:
#3 using np.arange(start,stop,step)
import numpy as np
print(np.arange(0,10,2))

[0 2 4 6 8]


In [96]:
#4 using np.linspace(start ,stop,num)
import numpy as np
print(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [98]:
# how to reshape a Numpy array?

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.reshape(1,9))
print(arr.reshape(3,3))

[[1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [101]:
#6. How do you flatten a muti-dimensional Numpy array?
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.flatten())
print(arr.ravel())

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [3]:
#7. How to generate a Numpy array of random numbers?
import numpy as np

print(np.random.rand(3,3))
print(np.random.randn(3,3))
print(np.random.randint(1, 10, (2, 2)))

[[0.72767776 0.71672927 0.75591164]
 [0.50192576 0.44592274 0.93442625]
 [0.10377902 0.32110935 0.33574729]]
[[ 0.38825716  1.9458439   1.55016729]
 [-0.31162663 -0.07552763 -0.96099254]
 [ 0.73600189 -0.80691317  0.83455639]]
[[1 7]
 [3 7]]


In [16]:
# How to compute mean, median, and standard deviation of an array?
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr.mean())
print(arr.std())
print(np.median(arr))

2.5
1.118033988749895
2.5


In [3]:
# Find indices of non zeros elements from [1,2,0,0,4,0]

import numpy as np
arr = np.array([1,2,0,0,1,0,5])
a = np.nonzero(arr)
print(a[0])

[0 1 4 6]


In [4]:
# Create a null vector of size 10

import numpy as np
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# Create a null vector of size one but the 5th value is one
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
# Reverse a vector(first element become last)

import numpy as np
vector = [1,2,3,4,0,0,1]
rev = vector[::-1]
print(rev)

[1, 0, 0, 4, 3, 2, 1]


In [13]:
# Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
matrix = [[1,2,3],[4,5,6],[0,7,8]]
matrix = np.reshape(range(9),(3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
# Create 3x3 identity matrix

import numpy as np
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
import numpy as np
a = np.random.randint(1,11,(10,10))
print(a.min())

1


In [25]:
# Create a 10x10 array with random values and find the maximum and minimum values

import numpy as np
a = np.random.randint(0,10,(10,10))
print(a)
print(np.min(a))
print(np.max(a))

[[4 7 2 9 1 5 6 4 5 7]
 [3 3 5 9 4 7 0 4 7 4]
 [9 7 5 6 1 6 0 5 2 8]
 [2 4 2 8 1 8 2 2 3 8]
 [6 5 5 9 7 3 4 8 2 0]
 [8 7 4 3 9 1 0 7 5 1]
 [0 4 8 7 4 8 4 6 1 6]
 [2 3 5 6 3 1 3 0 1 0]
 [2 5 5 5 9 2 1 3 2 3]
 [9 4 0 9 7 1 5 8 6 0]]
0
9


In [26]:
# Create a random vector of value 30 and find the mean value

import numpy as np
vector = np.random.random(30)
mean_value = np.mean(vector)
print(vector)
print(mean_value)

[0.26196048 0.25058483 0.39008997 0.92430865 0.14200276 0.45379733
 0.34813835 0.98330728 0.42553549 0.03818329 0.63868868 0.95099675
 0.08918986 0.16967834 0.57463356 0.21479216 0.83468862 0.64150728
 0.61111411 0.0032746  0.89965991 0.66856618 0.81338652 0.70249421
 0.02160982 0.01993955 0.94422593 0.31593127 0.24397109 0.24149988]
0.4605918914180238


In [35]:
#  Create a 2d array with 1 on border and 0 inside

import numpy as np
matrix = np.zeros((5,5))
matrix[0,:] = 1   #top row
matrix[-1,:] = 1  #bottom row
matrix[:,0] = 1   #left column
matrix[:,-1] = 1  #right column
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.T)
print(a.shape)
print(a.reshape(2,3))
print(a.reshape(1,6))
print(np.arange(1,20,2))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[ 1  3  5  7  9 11 13 15 17 19]


In [23]:
# 1. Array Manipulation
# Generate a 5x5 matrix where elements on the border are 1, and the inside is 0.
# Expected output:
#[[1. 1. 1. 1. 1.]
# [1, 0. 0. 0. 1.]
# [1. 0. 0. 0. 1.]
# [1. 0. 0. 0. 1.]
# [1. 1. 1. 1. 1.]]
#  Reshape a 1D array of 20 elements into a 4×5 matrix without using reshape().
# Rotate a given 4×4 NumPy array by 90 degrees counterclockwise.
# Flatten a 3D NumPy array into a 1D array.

import numpy as np
arr = np.zeros((5,5))
arr[0,:] = 1
arr[-1,:] = 1
arr[:,0] = 1
arr[:,-1] = 1
# arr[1:-1,1:-1] = 0
print(arr)

###🔹 Reshape a 1D array of 20 elements into a 4×5 matrix without using reshape().
a = np.arange(20) #Creating a 1D array with 20 elements
rows , cols = 4,5
matrix = [a[i*cols:(i+1)*cols]for i in range(rows)]
print(np.array(matrix))

###🔹 Rotate a given 4×4 NumPy array by 90 degrees counterclockwise.
array = np.arange(16).reshape(4,4)
rotated = np.rot90(array)
print(rotated)

###🔹 Flatten a 3D NumPy array into a 1D array.
array_3d = np.random.randint(0, 10, (2, 3, 4))  # Example 3D array (2×3×4)
flattened = array_3d.flatten()  # Convert to 1D
print(flattened)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
[5 6 5 7 4 3 3 1 1 9 8 2 8 5 2 5 5 1 5 8 7 4 5 0]


In [24]:
import numpy as np
arr = np.ones((4,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
